from pyo import *
s = Server().boot()
s.start()
m = Midictl(ctlnumber=[3, 4, 5], minscale=0, maxscale=127)
pp = Print(m, method=1, message="Audio stream value")
#p = Port(m, .02)
#a = Sine(freq=p, mul=.3).out()
#a1 = Sine(freq=p*1.25, mul=.3).out()
#a2 = Sine(freq=p*1.5, mul=.3).out()
s.gui(locals())